void draw_qa()
{
    TFile *fi_cld = new TFile("~/test_qa_cld.root","read");
    TFile *fi_fxt = new TFile("~/test_qa_fxt.root","read");

    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_b{(TH1D*)fi_cld->Get("h1_b"), (TH1D*)fi_fxt->Get("h1_b")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_prot_targ_N{(TH1D*)fi_cld->Get("h1_prot_targ_N"), (TH1D*)fi_fxt->Get("h1_prot_targ_N")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_prot_proj_N{(TH1D*)fi_cld->Get("h1_prot_proj_N"), (TH1D*)fi_fxt->Get("h1_prot_proj_N")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_prot_targ_proj_ratio{(TH1D*)fi_cld->Get("h1_prot_targ_proj_ratio"), (TH1D*)fi_fxt->Get("h1_prot_targ_proj_ratio")};

    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_hadr_pT{(TH1D*)fi_cld->Get("h1_hadr_pT"), (TH1D*)fi_fxt->Get("h1_hadr_pT")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_prot_pT{(TH1D*)fi_cld->Get("h1_prot_pT"), (TH1D*)fi_fxt->Get("h1_prot_pT")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_pionM_pT{(TH1D*)fi_cld->Get("h1_pionM_pT"), (TH1D*)fi_fxt->Get("h1_pionM_pT")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_pionP_pT{(TH1D*)fi_cld->Get("h1_pionP_pT"), (TH1D*)fi_fxt->Get("h1_pionP_pT")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_hadr_px{(TH1D*)fi_cld->Get("h1_hadr_px"), (TH1D*)fi_fxt->Get("h1_hadr_px")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_prot_px{(TH1D*)fi_cld->Get("h1_prot_px"), (TH1D*)fi_fxt->Get("h1_prot_px")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_pionM_px{(TH1D*)fi_cld->Get("h1_pionM_px"), (TH1D*)fi_fxt->Get("h1_pionM_px")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_pionP_px{(TH1D*)fi_cld->Get("h1_pionP_px"), (TH1D*)fi_fxt->Get("h1_pionP_px")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_hadr_py{(TH1D*)fi_cld->Get("h1_hadr_py"), (TH1D*)fi_fxt->Get("h1_hadr_py")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_prot_py{(TH1D*)fi_cld->Get("h1_prot_py"), (TH1D*)fi_fxt->Get("h1_prot_py")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_pionM_py{(TH1D*)fi_cld->Get("h1_pionM_py"), (TH1D*)fi_fxt->Get("h1_pionM_py")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_pionP_py{(TH1D*)fi_cld->Get("h1_pionP_py"), (TH1D*)fi_fxt->Get("h1_pionP_py")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_hadr_pz{(TH1D*)fi_cld->Get("h1_hadr_pz"), (TH1D*)fi_fxt->Get("h1_hadr_pz")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_prot_pz{(TH1D*)fi_cld->Get("h1_prot_pz"), (TH1D*)fi_fxt->Get("h1_prot_pz")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_pionM_pz{(TH1D*)fi_cld->Get("h1_pionM_pz"), (TH1D*)fi_fxt->Get("h1_pionM_pz")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_pionP_pz{(TH1D*)fi_cld->Get("h1_pionP_pz"), (TH1D*)fi_fxt->Get("h1_pionP_pz")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_hadr_y{(TH1D*)fi_cld->Get("h1_hadr_y"), (TH1D*)fi_fxt->Get("h1_hadr_y")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_prot_y{(TH1D*)fi_cld->Get("h1_prot_y"), (TH1D*)fi_fxt->Get("h1_prot_y")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_pionM_y{(TH1D*)fi_cld->Get("h1_pionM_y"), (TH1D*)fi_fxt->Get("h1_pionM_y")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_pionP_y{(TH1D*)fi_cld->Get("h1_pionP_y"), (TH1D*)fi_fxt->Get("h1_pionP_y")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_hadr_en{(TH1D*)fi_cld->Get("h1_hadr_en"), (TH1D*)fi_fxt->Get("h1_hadr_en")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_prot_en{(TH1D*)fi_cld->Get("h1_prot_en"), (TH1D*)fi_fxt->Get("h1_prot_en")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_pionM_en{(TH1D*)fi_cld->Get("h1_pionM_en"), (TH1D*)fi_fxt->Get("h1_pionM_en")};
    std::pair<std::unique_ptr<TH1D>,unique_ptr<TH1D>> h1_pionP_en{(TH1D*)fi_cld->Get("h1_pionP_en"), (TH1D*)fi_fxt->Get("h1_pionP_en")};

    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_hadr_dPhiPt{(TH2D*)fi_cld->Get("h2_hadr_dPhiPt"), (TH2D*)fi_fxt->Get("h2_hadr_dPhiPt")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_prot_dPhiPt{(TH2D*)fi_cld->Get("h2_prot_dPhiPt"), (TH2D*)fi_fxt->Get("h2_prot_dPhiPt")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionM_dPhiPt{(TH2D*)fi_cld->Get("h2_pionM_dPhiPt"), (TH2D*)fi_fxt->Get("h2_pionM_dPhiPt")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionP_dPhiPt{(TH2D*)fi_cld->Get("h2_pionP_dPhiPt"), (TH2D*)fi_fxt->Get("h2_pionP_dPhiPt")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_hadr_dPhiY{(TH2D*)fi_cld->Get("h2_hadr_dPhiY"), (TH2D*)fi_fxt->Get("h2_hadr_dPhiY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_prot_dPhiY{(TH2D*)fi_cld->Get("h2_prot_dPhiY"), (TH2D*)fi_fxt->Get("h2_prot_dPhiY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionM_dPhiY{(TH2D*)fi_cld->Get("h2_pionM_dPhiY"), (TH2D*)fi_fxt->Get("h2_pionM_dPhiY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionP_dPhiY{(TH2D*)fi_cld->Get("h2_pionP_dPhiY"), (TH2D*)fi_fxt->Get("h2_pionP_dPhiY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_hadr_dPhipz{(TH2D*)fi_cld->Get("h2_hadr_dPhipz"), (TH2D*)fi_fxt->Get("h2_hadr_dPhipz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_prot_dPhipz{(TH2D*)fi_cld->Get("h2_prot_dPhipz"), (TH2D*)fi_fxt->Get("h2_prot_dPhipz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionM_dPhipz{(TH2D*)fi_cld->Get("h2_pionM_dPhipz"), (TH2D*)fi_fxt->Get("h2_pionM_dPhipz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionP_dPhipz{(TH2D*)fi_cld->Get("h2_pionP_dPhipz"), (TH2D*)fi_fxt->Get("h2_pionP_dPhipz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_hadr_pTY{(TH2D*)fi_cld->Get("h2_hadr_pTY"), (TH2D*)fi_fxt->Get("h2_hadr_pTY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_prot_pTY{(TH2D*)fi_cld->Get("h2_prot_pTY"), (TH2D*)fi_fxt->Get("h2_prot_pTY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionM_pTY{(TH2D*)fi_cld->Get("h2_pionM_pTY"), (TH2D*)fi_fxt->Get("h2_pionM_pTY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionP_pTY{(TH2D*)fi_cld->Get("h2_pionP_pTY"), (TH2D*)fi_fxt->Get("h2_pionP_pTY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_hadr_pxY{(TH2D*)fi_cld->Get("h2_hadr_pxY"), (TH2D*)fi_fxt->Get("h2_hadr_pxY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_prot_pxY{(TH2D*)fi_cld->Get("h2_prot_pxY"), (TH2D*)fi_fxt->Get("h2_prot_pxY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionM_pxY{(TH2D*)fi_cld->Get("h2_pionM_pxY"), (TH2D*)fi_fxt->Get("h2_pionM_pxY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionP_pxY{(TH2D*)fi_cld->Get("h2_pionP_pxY"), (TH2D*)fi_fxt->Get("h2_pionP_pxY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_hadr_pyY{(TH2D*)fi_cld->Get("h2_hadr_pyY"), (TH2D*)fi_fxt->Get("h2_hadr_pyY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_prot_pyY{(TH2D*)fi_cld->Get("h2_prot_pyY"), (TH2D*)fi_fxt->Get("h2_prot_pyY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionM_pyY{(TH2D*)fi_cld->Get("h2_pionM_pyY"), (TH2D*)fi_fxt->Get("h2_pionM_pyY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionP_pyY{(TH2D*)fi_cld->Get("h2_pionP_pyY"), (TH2D*)fi_fxt->Get("h2_pionP_pyY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_hadr_pzY{(TH2D*)fi_cld->Get("h2_hadr_pzY"), (TH2D*)fi_fxt->Get("h2_hadr_pzY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_prot_pzY{(TH2D*)fi_cld->Get("h2_prot_pzY"), (TH2D*)fi_fxt->Get("h2_prot_pzY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionM_pzY{(TH2D*)fi_cld->Get("h2_pionM_pzY"), (TH2D*)fi_fxt->Get("h2_pionM_pzY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionP_pzY{(TH2D*)fi_cld->Get("h2_pionP_pzY"), (TH2D*)fi_fxt->Get("h2_pionP_pzY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_hadr_enY{(TH2D*)fi_cld->Get("h2_hadr_enY"), (TH2D*)fi_fxt->Get("h2_hadr_enY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_prot_enY{(TH2D*)fi_cld->Get("h2_prot_enY"), (TH2D*)fi_fxt->Get("h2_prot_enY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionM_enY{(TH2D*)fi_cld->Get("h2_pionM_enY"), (TH2D*)fi_fxt->Get("h2_pionM_enY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionP_enY{(TH2D*)fi_cld->Get("h2_pionP_enY"), (TH2D*)fi_fxt->Get("h2_pionP_enY")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_hadr_pTpz{(TH2D*)fi_cld->Get("h2_hadr_pTpz"), (TH2D*)fi_fxt->Get("h2_hadr_pTpz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_prot_pTpz{(TH2D*)fi_cld->Get("h2_prot_pTpz"), (TH2D*)fi_fxt->Get("h2_prot_pTpz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionM_pTpz{(TH2D*)fi_cld->Get("h2_pionM_pTpz"), (TH2D*)fi_fxt->Get("h2_pionM_pTpz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionP_pTpz{(TH2D*)fi_cld->Get("h2_pionP_pTpz"), (TH2D*)fi_fxt->Get("h2_pionP_pTpz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_hadr_pxpz{(TH2D*)fi_cld->Get("h2_hadr_pxpz"), (TH2D*)fi_fxt->Get("h2_hadr_pxpz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_prot_pxpz{(TH2D*)fi_cld->Get("h2_prot_pxpz"), (TH2D*)fi_fxt->Get("h2_prot_pxpz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionM_pxpz{(TH2D*)fi_cld->Get("h2_pionM_pxpz"), (TH2D*)fi_fxt->Get("h2_pionM_pxpz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionP_pxpz{(TH2D*)fi_cld->Get("h2_pionP_pxpz"), (TH2D*)fi_fxt->Get("h2_pionP_pxpz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_hadr_pypz{(TH2D*)fi_cld->Get("h2_hadr_pypz"), (TH2D*)fi_fxt->Get("h2_hadr_pypz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_prot_pypz{(TH2D*)fi_cld->Get("h2_prot_pypz"), (TH2D*)fi_fxt->Get("h2_prot_pypz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionM_pypz{(TH2D*)fi_cld->Get("h2_pionM_pypz"), (TH2D*)fi_fxt->Get("h2_pionM_pypz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionP_pypz{(TH2D*)fi_cld->Get("h2_pionP_pypz"), (TH2D*)fi_fxt->Get("h2_pionP_pypz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_hadr_enpz{(TH2D*)fi_cld->Get("h2_hadr_enpz"), (TH2D*)fi_fxt->Get("h2_hadr_enpz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_prot_enpz{(TH2D*)fi_cld->Get("h2_prot_enpz"), (TH2D*)fi_fxt->Get("h2_prot_enpz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionM_enpz{(TH2D*)fi_cld->Get("h2_pionM_enpz"), (TH2D*)fi_fxt->Get("h2_pionM_enpz")};
    std::pair<std::unique_ptr<TH2D>,unique_ptr<TH2D>> h2_pionP_enpz{(TH2D*)fi_cld->Get("h2_pionP_enpz"), (TH2D*)fi_fxt->Get("h2_pionP_enpz")};

    h1_b.first->SetLineColor(kRed+1); h1_b.second->SetLineColor(kBlue+1);
    h1_prot_targ_N.first->SetLineColor(kRed+1); h1_prot_targ_N.second->SetLineColor(kBlue+1);
    h1_prot_proj_N.first->SetLineColor(kRed+1); h1_prot_proj_N.second->SetLineColor(kBlue+1);
    h1_prot_targ_proj_ratio.first->SetLineColor(kRed+1); h1_prot_targ_proj_ratio.second->SetLineColor(kBlue+1);

    h1_hadr_pT.first->SetLineColor(kRed+1); h1_hadr_pT.second->SetLineColor(kBlue+1);
    h1_prot_pT.first->SetLineColor(kRed+1); h1_prot_pT.second->SetLineColor(kBlue+1);
    h1_pionM_pT.first->SetLineColor(kRed+1); h1_pionM_pT.second->SetLineColor(kBlue+1);
    h1_pionP_pT.first->SetLineColor(kRed+1); h1_pionP_pT.second->SetLineColor(kBlue+1);
    h1_hadr_px.first->SetLineColor(kRed+1); h1_hadr_px.second->SetLineColor(kBlue+1);
    h1_prot_px.first->SetLineColor(kRed+1); h1_prot_px.second->SetLineColor(kBlue+1);
    h1_pionM_px.first->SetLineColor(kRed+1); h1_pionM_px.second->SetLineColor(kBlue+1);
    h1_pionP_px.first->SetLineColor(kRed+1); h1_pionP_px.second->SetLineColor(kBlue+1);
    h1_hadr_py.first->SetLineColor(kRed+1); h1_hadr_py.second->SetLineColor(kBlue+1);
    h1_prot_py.first->SetLineColor(kRed+1); h1_prot_py.second->SetLineColor(kBlue+1);
    h1_pionM_py.first->SetLineColor(kRed+1); h1_pionM_py.second->SetLineColor(kBlue+1);
    h1_pionP_py.first->SetLineColor(kRed+1); h1_pionP_py.second->SetLineColor(kBlue+1);
    h1_hadr_pz.first->SetLineColor(kRed+1); h1_hadr_pz.second->SetLineColor(kBlue+1);
    h1_prot_pz.first->SetLineColor(kRed+1); h1_prot_pz.second->SetLineColor(kBlue+1);
    h1_pionM_pz.first->SetLineColor(kRed+1); h1_pionM_pz.second->SetLineColor(kBlue+1);
    h1_pionP_pz.first->SetLineColor(kRed+1); h1_pionP_pz.second->SetLineColor(kBlue+1);
    h1_hadr_y.first->SetLineColor(kRed+1); h1_hadr_y.second->SetLineColor(kBlue+1);
    h1_prot_y.first->SetLineColor(kRed+1); h1_prot_y.second->SetLineColor(kBlue+1);
    h1_pionM_y.first->SetLineColor(kRed+1); h1_pionM_y.second->SetLineColor(kBlue+1);
    h1_pionP_y.first->SetLineColor(kRed+1); h1_pionP_y.second->SetLineColor(kBlue+1);
    h1_hadr_en.first->SetLineColor(kRed+1); h1_hadr_en.second->SetLineColor(kBlue+1);
    h1_prot_en.first->SetLineColor(kRed+1); h1_prot_en.second->SetLineColor(kBlue+1);
    h1_pionM_en.first->SetLineColor(kRed+1); h1_pionM_en.second->SetLineColor(kBlue+1);
    h1_pionP_en.first->SetLineColor(kRed+1); h1_pionP_en.second->SetLineColor(kBlue+1);

    h1_prot_targ_N.first->GetXaxis()->SetRangeUser(0.,50.); h1_prot_targ_N.second->GetXaxis()->SetRangeUser(0.,50.);
    h1_prot_targ_N.first->GetYaxis()->SetRangeUser(0.,900.); h1_prot_targ_N.second->GetYaxis()->SetRangeUser(0.,900.);
    h1_prot_proj_N.first->GetXaxis()->SetRangeUser(0.,50.); h1_prot_proj_N.second->GetXaxis()->SetRangeUser(0.,50.);
    h1_prot_proj_N.first->GetYaxis()->SetRangeUser(0.,900.); h1_prot_proj_N.second->GetYaxis()->SetRangeUser(0.,900.);
    h1_prot_targ_proj_ratio.first->GetXaxis()->SetRangeUser(0.,15.); h1_prot_targ_proj_ratio.second->GetXaxis()->SetRangeUser(0.,15.);

    h2_hadr_pTY.first->GetXaxis()->SetRangeUser(-1.6,1.6); h2_hadr_pTY.second->GetXaxis()->SetRangeUser(-1.6,1.6); 
    h2_hadr_pTY.first->GetYaxis()->SetRangeUser(0.,2.); h2_hadr_pTY.second->GetYaxis()->SetRangeUser(0.,2.); 
    h2_prot_pTY.first->GetXaxis()->SetRangeUser(-1.6,1.6); h2_prot_pTY.second->GetXaxis()->SetRangeUser(-1.6,1.6); 
    h2_prot_pTY.first->GetYaxis()->SetRangeUser(0.,2.); h2_prot_pTY.second->GetYaxis()->SetRangeUser(0.,2.);
    h2_pionM_pTY.first->GetXaxis()->SetRangeUser(-2.,2.); h2_pionM_pTY.second->GetXaxis()->SetRangeUser(-2.,2.); 
    h2_pionM_pTY.first->GetYaxis()->SetRangeUser(0.,1.); h2_pionM_pTY.second->GetYaxis()->SetRangeUser(0.,1.);
    h2_pionP_pTY.first->GetXaxis()->SetRangeUser(-2.,2.); h2_pionP_pTY.second->GetXaxis()->SetRangeUser(-2.,2.); 
    h2_pionP_pTY.first->GetYaxis()->SetRangeUser(0.,1.); h2_pionP_pTY.second->GetYaxis()->SetRangeUser(0.,1.);

    gSystem->Exec("mkdir -p ./draw");

    TCanvas *canv_700x500 = new TCanvas("canv_700x500", "canv_700x500", 700, 500);

    canv_700x500->cd();

    h1_b.first->Draw(); h1_b.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_b.first->GetName()));
    h1_prot_targ_N.first->Draw(); h1_prot_targ_N.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_prot_targ_N.first->GetName()));
    h1_prot_proj_N.first->Draw(); h1_prot_proj_N.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_prot_proj_N.first->GetName()));
    h1_prot_targ_proj_ratio.first->Draw(); h1_prot_targ_proj_ratio.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_prot_targ_proj_ratio.first->GetName()));

    canv_700x500->SetLogy(true);
    h1_hadr_pT.first->Draw(); h1_hadr_pT.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_hadr_pT.first->GetName()));
    h1_prot_pT.first->Draw(); h1_prot_pT.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_prot_pT.first->GetName()));
    h1_pionM_pT.first->Draw(); h1_pionM_pT.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_pionM_pT.first->GetName()));
    h1_pionP_pT.first->Draw(); h1_pionP_pT.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_pionP_pT.first->GetName()));
    h1_hadr_px.first->Draw(); h1_hadr_px.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_hadr_px.first->GetName()));
    h1_prot_px.first->Draw(); h1_prot_px.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_prot_px.first->GetName()));
    h1_pionM_px.first->Draw(); h1_pionM_px.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_pionM_px.first->GetName()));
    h1_pionP_px.first->Draw(); h1_pionP_px.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_pionP_px.first->GetName()));
    h1_hadr_py.first->Draw(); h1_hadr_py.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_hadr_py.first->GetName()));
    h1_prot_py.first->Draw(); h1_prot_py.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_prot_py.first->GetName()));
    h1_pionM_py.first->Draw(); h1_pionM_py.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_pionM_py.first->GetName()));
    h1_pionP_py.first->Draw(); h1_pionP_py.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_pionP_py.first->GetName()));
    h1_hadr_pz.first->Draw(); h1_hadr_pz.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_hadr_pz.first->GetName()));
    h1_prot_pz.first->Draw(); h1_prot_pz.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_prot_pz.first->GetName()));
    h1_pionM_pz.first->Draw(); h1_pionM_pz.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_pionM_pz.first->GetName()));
    h1_pionP_pz.first->Draw(); h1_pionP_pz.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_pionP_pz.first->GetName()));
    h1_hadr_y.first->Draw(); h1_hadr_y.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_hadr_y.first->GetName()));
    h1_prot_y.first->Draw(); h1_prot_y.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_prot_y.first->GetName()));
    h1_pionM_y.first->Draw(); h1_pionM_y.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_pionM_y.first->GetName()));
    h1_pionP_y.first->Draw(); h1_pionP_y.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_pionP_y.first->GetName()));
    h1_hadr_en.first->Draw(); h1_hadr_en.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_hadr_en.first->GetName()));
    h1_prot_en.first->Draw(); h1_prot_en.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_prot_en.first->GetName()));
    h1_pionM_en.first->Draw(); h1_pionM_en.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_pionM_en.first->GetName()));
    h1_pionP_en.first->Draw(); h1_pionP_en.second->Draw("same");
    canv_700x500->SaveAs(Form("./draw/c_%s.png", h1_pionP_en.first->GetName()));

    canv_700x500->SetLogy(false);
    canv_700x500->SetLogz();

    h2_hadr_dPhiPt.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_hadr_dPhiPt.first->GetName()));
    h2_hadr_dPhiPt.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_hadr_dPhiPt.second->GetName()));
    h2_prot_dPhiPt.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_prot_dPhiPt.first->GetName()));
    h2_prot_dPhiPt.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_prot_dPhiPt.second->GetName()));
    h2_pionM_dPhiPt.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionM_dPhiPt.first->GetName()));
    h2_pionM_dPhiPt.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionM_dPhiPt.second->GetName()));
    h2_pionP_dPhiPt.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionP_dPhiPt.first->GetName()));
    h2_pionP_dPhiPt.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionP_dPhiPt.second->GetName()));
    h2_hadr_dPhiY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_hadr_dPhiY.first->GetName()));
    h2_hadr_dPhiY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_hadr_dPhiY.second->GetName()));
    h2_prot_dPhiY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_prot_dPhiY.first->GetName()));
    h2_prot_dPhiY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_prot_dPhiY.second->GetName()));
    h2_pionM_dPhiY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionM_dPhiY.first->GetName()));
    h2_pionM_dPhiY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionM_dPhiY.second->GetName()));
    h2_pionP_dPhiY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionP_dPhiY.first->GetName()));
    h2_pionP_dPhiY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionP_dPhiY.second->GetName()));
    h2_hadr_dPhipz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_hadr_dPhipz.first->GetName()));
    h2_hadr_dPhipz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_hadr_dPhipz.second->GetName()));
    h2_prot_dPhipz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_prot_dPhipz.first->GetName()));
    h2_prot_dPhipz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_prot_dPhipz.second->GetName()));
    h2_pionM_dPhipz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionM_dPhipz.first->GetName()));
    h2_pionM_dPhipz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionM_dPhipz.second->GetName()));
    h2_pionP_dPhipz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionP_dPhipz.first->GetName()));
    h2_pionP_dPhipz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionP_dPhipz.second->GetName()));
    h2_hadr_pTY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_hadr_pTY.first->GetName()));
    h2_hadr_pTY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_hadr_pTY.second->GetName()));
    h2_prot_pTY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_prot_pTY.first->GetName()));
    h2_prot_pTY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_prot_pTY.second->GetName()));
    h2_pionM_pTY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionM_pTY.first->GetName()));
    h2_pionM_pTY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionM_pTY.second->GetName()));
    h2_pionP_pTY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionP_pTY.first->GetName()));
    h2_pionP_pTY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionP_pTY.second->GetName()));
    h2_hadr_pxY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_hadr_pxY.first->GetName()));
    h2_hadr_pxY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_hadr_pxY.second->GetName()));
    h2_prot_pxY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_prot_pxY.first->GetName()));
    h2_prot_pxY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_prot_pxY.second->GetName()));
    h2_pionM_pxY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionM_pxY.first->GetName()));
    h2_pionM_pxY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionM_pxY.second->GetName()));
    h2_pionP_pxY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionP_pxY.first->GetName()));
    h2_pionP_pxY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionP_pxY.second->GetName()));
    h2_hadr_pyY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_hadr_pyY.first->GetName()));
    h2_hadr_pyY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_hadr_pyY.second->GetName()));
    h2_prot_pyY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_prot_pyY.first->GetName()));
    h2_prot_pyY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_prot_pyY.second->GetName()));
    h2_pionM_pyY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionM_pyY.first->GetName()));
    h2_pionM_pyY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionM_pyY.second->GetName()));
    h2_pionP_pyY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionP_pyY.first->GetName()));
    h2_pionP_pyY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionP_pyY.second->GetName()));
    h2_hadr_pzY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_hadr_pzY.first->GetName()));
    h2_hadr_pzY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_hadr_pzY.second->GetName()));
    h2_prot_pzY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_prot_pzY.first->GetName()));
    h2_prot_pzY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_prot_pzY.second->GetName()));
    h2_pionM_pzY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionM_pzY.first->GetName()));
    h2_pionM_pzY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionM_pzY.second->GetName()));
    h2_pionP_pzY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionP_pzY.first->GetName()));
    h2_pionP_pzY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionP_pzY.second->GetName()));
    h2_hadr_enY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_hadr_enY.first->GetName()));
    h2_hadr_enY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_hadr_enY.second->GetName()));
    h2_prot_enY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_prot_enY.first->GetName()));
    h2_prot_enY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_prot_enY.second->GetName()));
    h2_pionM_enY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionM_enY.first->GetName()));
    h2_pionM_enY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionM_enY.second->GetName()));
    h2_pionP_enY.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionP_enY.first->GetName()));
    h2_pionP_enY.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionP_enY.second->GetName()));
    h2_hadr_pTpz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_hadr_pTpz.first->GetName()));
    h2_hadr_pTpz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_hadr_pTpz.second->GetName()));
    h2_prot_pTpz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_prot_pTpz.first->GetName()));
    h2_prot_pTpz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_prot_pTpz.second->GetName()));
    h2_pionM_pTpz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionM_pTpz.first->GetName()));
    h2_pionM_pTpz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionM_pTpz.second->GetName()));
    h2_pionP_pTpz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionP_pTpz.first->GetName()));
    h2_pionP_pTpz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionP_pTpz.second->GetName()));
    h2_hadr_pxpz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_hadr_pxpz.first->GetName()));
    h2_hadr_pxpz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_hadr_pxpz.second->GetName()));
    h2_prot_pxpz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_prot_pxpz.first->GetName()));
    h2_prot_pxpz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_prot_pxpz.second->GetName()));
    h2_pionM_pxpz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionM_pxpz.first->GetName()));
    h2_pionM_pxpz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionM_pxpz.second->GetName()));
    h2_pionP_pxpz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionP_pxpz.first->GetName()));
    h2_pionP_pxpz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionP_pxpz.second->GetName()));
    h2_hadr_pypz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_hadr_pypz.first->GetName()));
    h2_hadr_pypz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_hadr_pypz.second->GetName()));
    h2_prot_pypz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_prot_pypz.first->GetName()));
    h2_prot_pypz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_prot_pypz.second->GetName()));
    h2_pionM_pypz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionM_pypz.first->GetName()));
    h2_pionM_pypz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionM_pypz.second->GetName()));
    h2_pionP_pypz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionP_pypz.first->GetName()));
    h2_pionP_pypz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionP_pypz.second->GetName()));
    h2_hadr_enpz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_hadr_enpz.first->GetName()));
    h2_hadr_enpz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_hadr_enpz.second->GetName()));
    h2_prot_enpz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_prot_enpz.first->GetName()));
    h2_prot_enpz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_prot_enpz.second->GetName()));
    h2_pionM_enpz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionM_enpz.first->GetName()));
    h2_pionM_enpz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionM_enpz.second->GetName()));
    h2_pionP_enpz.first->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_cld.png", h2_pionP_enpz.first->GetName()));
    h2_pionP_enpz.second->Draw("colz");
    canv_700x500->SaveAs(Form("./draw/c_%s_fxt.png", h2_pionP_enpz.second->GetName()));
}